language: python
python:
  - "2.7"

services:
  - postgresql

addons:
  postgresql: "9.4"

install:
  - pip install -r requirements-group6.txt

before_script:
  - "export DISPLAY=:99.0"
  - psql -c "CREATE USER oscar WITH PASSWORD 'oscar' CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE oscar OWNER oscar;" -U postgres
  - python manage.py makemigrations
  - chmod +x makemigrations.sh
  - ./makemigrations.sh
  - python manage.py migrate

script:
  # General Behaviour Testing
  - python manage.py behave
  # Targeted Unit Testing
  - python manage.py test questions_factory
  # Coverage
  - coverage run --source=questions_factory manage.py behave
  - coverage run --source=questions_factory manage.py test questions_factory

after_success:
    coveralls
